<a href="https://colab.research.google.com/github/tradertanmay/FinanceProjects/blob/master/neural_network_lineaaaar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout


Using TensorFlow backend.


In [0]:
x_train = np.array([[i] for i in range (1,100)])

In [0]:
x_test =np.array([[i] for i in range (100,199)])

In [0]:
y_train = np.array([[i] for i in range (1,100)])

In [0]:
y_test = np.array([[i] for i in range (100,199)])

In [0]:
model = Sequential()
model.add(Dense(2,input_dim=1,activation='relu'))
model.add(Dense(1,activation='relu'))

In [0]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['accuracy'])

In [129]:
model.fit(x_train, y_train,epochs= 1000)

Epoch 1/1000
99/99 [==============================] - 1s 7ms/step - loss: 386.5601 - acc: 0.0101
Epoch 2/1000
99/99 [==============================] - 0s 100us/step - loss: 367.6054 - acc: 0.0101
Epoch 3/1000
99/99 [==============================] - 0s 118us/step - loss: 348.3864 - acc: 0.0101
Epoch 4/1000
99/99 [==============================] - 0s 138us/step - loss: 329.4536 - acc: 0.0101
Epoch 5/1000
99/99 [==============================] - 0s 98us/step - loss: 311.0760 - acc: 0.0101
Epoch 6/1000
99/99 [==============================] - 0s 114us/step - loss: 293.1081 - acc: 0.0101
Epoch 7/1000
99/99 [==============================] - 0s 123us/step - loss: 275.4834 - acc: 0.0101
Epoch 8/1000
99/99 [==============================] - 0s 99us/step - loss: 259.0034 - acc: 0.0202
Epoch 9/1000
99/99 [==============================] - 0s 99us/step - loss: 243.2623 - acc: 0.0202
Epoch 10/1000
99/99 [==============================] - 0s 100us/step - loss: 228.3102 - acc: 0.0202
Epoch 11/1000


In [118]:
model.predict(x_test)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [0]:
x_train = np.array([[i,i] for i in range (1,100)])

In [84]:
x_train

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10],
       [11, 11],
       [12, 12],
       [13, 13],
       [14, 14],
       [15, 15],
       [16, 16],
       [17, 17],
       [18, 18],
       [19, 19],
       [20, 20],
       [21, 21],
       [22, 22],
       [23, 23],
       [24, 24],
       [25, 25],
       [26, 26],
       [27, 27],
       [28, 28],
       [29, 29],
       [30, 30],
       [31, 31],
       [32, 32],
       [33, 33],
       [34, 34],
       [35, 35],
       [36, 36],
       [37, 37],
       [38, 38],
       [39, 39],
       [40, 40],
       [41, 41],
       [42, 42],
       [43, 43],
       [44, 44],
       [45, 45],
       [46, 46],
       [47, 47],
       [48, 48],
       [49, 49],
       [50, 50],
       [51, 51],
       [52, 52],
       [53, 53],
       [54, 54],
       [55, 55],
       [56, 56],
       [57, 57],
       [58, 58],
       [59, 59

In [30]:
x_train

array([[1],
       [2],
       [3]])

In [0]:
s = np.array([[i] for i in range (1,5)])

In [32]:
s

array([[1],
       [2],
       [3],
       [4]])